# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20190518_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image']},
        ),
        migrations.AddField(
            model_name='profile',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
